import type { ComprehensiveWasteTaxonomy } from './types';

export const comprehensivePresets: ComprehensiveWasteTaxonomy[] = [
  // CATEGORY 1: PLASTIC (Recyclable)
  {
    id: 'preset-pl-01',
    x: 32,
    y: 22,
    width: 36,
    height: 52,
    itemName: 'PET Plastic Beverage Bottle',
    confidence: 98.4,
    categoryCode: 'PL-01',
    categoryName: 'CATEGORY 1: PLASTIC (Recyclable)',
    subType: 'PET',
    bengaliExample: 'পানির বোতল, কোল্ড ড্রিংক বোতল',
    natureCategory: 'Inorganic / Non-biodegradable',
    compositionDetail: 'Polyethylene Terephthalate (#1 PET Resin Container)',
    operationalStream: 'RECYCLABLE',
    processingPathway: 'Mechanical Washing, Flaking & Re-extrusion into recycled PET granules',
    physicalState: 'Solid',
    environmentalRisk: 'High recyclability value; clean separation prevents microplastic leaching.',
    color: '#3b82f6',
    badgeLabel: 'PL-01 • PET PLASTIC',
    weightGrams: 38
  },
  {
    id: 'preset-pl-02',
    x: 34,
    y: 24,
    width: 34,
    height: 50,
    itemName: 'HDPE Detergent & Milk Jug Container',
    confidence: 97.5,
    categoryCode: 'PL-02',
    categoryName: 'CATEGORY 1: PLASTIC (Recyclable)',
    subType: 'HDPE',
    bengaliExample: 'শ্যাম্পু/ডিটারজেন্ট বোতল, দুধের জার',
    natureCategory: 'Inorganic / Non-biodegradable',
    compositionDetail: 'High-Density Polyethylene (#2 Polymer Resin)',
    operationalStream: 'RECYCLABLE',
    processingPathway: 'Shredding, Hot Chemical Wash & Granulation into HDPE lumber/pipes',
    physicalState: 'Solid',
    environmentalRisk: 'Chemical residues must be rinsed before processing to maintain purity.',
    color: '#3b82f6',
    badgeLabel: 'PL-02 • HDPE PLASTIC',
    weightGrams: 85
  },
  {
    id: 'preset-pl-05',
    x: 33,
    y: 25,
    width: 35,
    height: 48,
    itemName: 'LDPE Polyethylene Packaging Bag',
    confidence: 95.2,
    categoryCode: 'PL-05',
    categoryName: 'CATEGORY 1: PLASTIC (Recyclable)',
    subType: 'LDPE',
    bengaliExample: 'পলিথিন ব্যাগ (কিছু ক্ষেত্রে reusable)',
    natureCategory: 'Inorganic / Non-biodegradable',
    compositionDetail: 'Low-Density Polyethylene (#4 Flexible Film)',
    operationalStream: 'RECYCLABLE',
    processingPathway: 'Film Agglomeration & Pelletizing for secondary industrial packaging',
    physicalState: 'Solid',
    environmentalRisk: 'Clogs mechanical MRF sorters if mixed loosely with rigid plastics.',
    color: '#0ea5e9',
    badgeLabel: 'PL-05 • LDPE FILM',
    weightGrams: 12
  },

  // CATEGORY 2: PAPER & CARDBOARD (Recyclable)
  {
    id: 'preset-pa-01',
    x: 30,
    y: 20,
    width: 40,
    height: 55,
    itemName: 'Corrugated Cardboard Shipping Box',
    confidence: 98.1,
    categoryCode: 'PA-01',
    categoryName: 'CATEGORY 2: PAPER & CARDBOARD (Recyclable)',
    subType: 'Cardboard',
    bengaliExample: 'কার্টন বক্স',
    natureCategory: 'Inorganic / Non-biodegradable',
    compositionDetail: 'Multi-layer Kraft Paper & Cellulose Fiber Matrix',
    operationalStream: 'RECYCLABLE',
    processingPathway: 'Hydrapulper Slurry Screening, De-inking & Pulp Re-forming into new boxes',
    physicalState: 'Solid',
    environmentalRisk: 'High recycling yield; must be kept dry and free from oil/grease.',
    color: '#06b6d4',
    badgeLabel: 'PA-01 • CARDBOARD BOX',
    weightGrams: 240
  },
  {
    id: 'preset-pa-03',
    x: 32,
    y: 24,
    width: 36,
    height: 50,
    itemName: 'Printed Office Document & Notebook Paper',
    confidence: 96.8,
    categoryCode: 'PA-03',
    categoryName: 'CATEGORY 2: PAPER & CARDBOARD (Recyclable)',
    subType: 'Office Paper',
    bengaliExample: 'সাদা কাগজ, বই',
    natureCategory: 'Inorganic / Non-biodegradable',
    compositionDetail: 'High-Grade Bleached Cellulose Wood Pulp & Printer Ink',
    operationalStream: 'RECYCLABLE',
    processingPathway: 'Flotation De-inking & Pulp Refining into stationery grades',
    physicalState: 'Solid',
    environmentalRisk: 'Fibers degrade after 5-7 recycling loops; requires proper segregation.',
    color: '#06b6d4',
    badgeLabel: 'PA-03 • OFFICE PAPER',
    weightGrams: 45
  },

  // CATEGORY 3: GLASS (Recyclable)
  {
    id: 'preset-gl-01',
    x: 34,
    y: 22,
    width: 32,
    height: 54,
    itemName: 'Clear Glass Water & Medicine Bottle',
    confidence: 97.9,
    categoryCode: 'GL-01',
    categoryName: 'CATEGORY 3: GLASS (Recyclable)',
    subType: 'Clear Glass',
    bengaliExample: 'পানির/মেডিসিন বোতল',
    natureCategory: 'Inorganic / Non-biodegradable',
    compositionDetail: 'Silica Sand, Soda Ash, and Limestone Cullet Structure',
    operationalStream: 'RECYCLABLE',
    processingPathway: 'Optical Color Sorting, Crushing to Cullet & Furnace Melting at 1500°C',
    physicalState: 'Solid',
    environmentalRisk: '100% infinitely recyclable without loss of quality or structural integrity.',
    color: '#14b8a6',
    badgeLabel: 'GL-01 • CLEAR GLASS',
    weightGrams: 310
  },

  // CATEGORY 4: METAL (Recyclable)
  {
    id: 'preset-me-01',
    x: 35,
    y: 26,
    width: 30,
    height: 46,
    itemName: 'Aluminum Beverage & Soda Can',
    confidence: 98.6,
    categoryCode: 'ME-01',
    categoryName: 'CATEGORY 4: METAL (Recyclable)',
    subType: 'Aluminum',
    bengaliExample: 'কোল্ড ড্রিংক ক্যান',
    natureCategory: 'Inorganic / Non-biodegradable',
    compositionDetail: 'Pure Aluminum Alloy & Food-Grade Protective Lacquer Coating',
    operationalStream: 'RECYCLABLE',
    processingPathway: 'Eddy Current Separation, De-coating Induction Smelting & Ingot Casting',
    physicalState: 'Solid',
    environmentalRisk: 'Recycling saves 95% of the energy required to smelt virgin bauxite ore.',
    color: '#6366f1',
    badgeLabel: 'ME-01 • ALUMINUM CAN',
    weightGrams: 14
  },
  {
    id: 'preset-me-02',
    x: 34,
    y: 25,
    width: 32,
    height: 48,
    itemName: 'Steel / Tin Food Packaging Can',
    confidence: 97.1,
    categoryCode: 'ME-02',
    categoryName: 'CATEGORY 4: METAL (Recyclable)',
    subType: 'Steel/Tin',
    bengaliExample: 'ফুড ক্যান',
    natureCategory: 'Inorganic / Non-biodegradable',
    compositionDetail: 'Low-Carbon Ferrous Steel with Tinplate Layer',
    operationalStream: 'RECYCLABLE',
    processingPathway: 'Electromagnetic Sorting & Electric Arc Furnace Smelting',
    physicalState: 'Solid',
    environmentalRisk: 'Highly magnetic; easily recoverable from municipal solid waste streams.',
    color: '#6366f1',
    badgeLabel: 'ME-02 • FERROUS TIN CAN',
    weightGrams: 95
  },

  // CATEGORY 5: E-WASTE (High-value Recyclable)
  {
    id: 'preset-ew-02',
    x: 31,
    y: 23,
    width: 38,
    height: 52,
    itemName: 'Computer / Motherboard Circuit PCB',
    confidence: 98.8,
    categoryCode: 'EW-02',
    categoryName: 'CATEGORY 5: E-WASTE (High-value Recyclable)',
    subType: 'Circuit/PCB',
    bengaliExample: 'কম্পিউটার/মোবাইল সার্কিট বোর্ড, চিপস',
    natureCategory: 'Hazardous / Toxic',
    compositionDetail: 'Precious Metals (Gold, Silver, Palladium), Copper Trace & Fiberglass Substrate',
    operationalStream: 'HAZARDOUS_SPECIAL',
    processingPathway: 'Hydrometallurgical Precious Metal Recovery & Toxic Resin Stabilization',
    physicalState: 'Solid',
    environmentalRisk: 'Contains toxic brominated flame retardants & heavy metals; high recovery value.',
    color: '#a855f7',
    badgeLabel: 'EW-02 • PCB CIRCUIT BOARD',
    weightGrams: 210
  },
  {
    id: 'preset-ew-04',
    x: 33,
    y: 25,
    width: 34,
    height: 50,
    itemName: 'Smartphone & Discarded Charger Device',
    confidence: 97.4,
    categoryCode: 'EW-04',
    categoryName: 'CATEGORY 5: E-WASTE (High-value Recyclable)',
    subType: 'Small Devices',
    bengaliExample: 'ফোন, চার্জার',
    natureCategory: 'Hazardous / Toxic',
    compositionDetail: 'Lithium Battery Pack, Copper Wiring, Rare Earth Elements & Polycarbonate',
    operationalStream: 'HAZARDOUS_SPECIAL',
    processingPathway: 'Manual Robotic Dismantling, Battery Extraction & Multi-Metal Refining',
    physicalState: 'Solid',
    environmentalRisk: 'CRITICAL RISK: Flammable lithium battery thermal runaway & groundwater toxicity.',
    color: '#a855f7',
    badgeLabel: 'EW-04 • SMALL E-DEVICE',
    weightGrams: 165
  },

  // CATEGORY 6: TEXTILE (Reusable)
  {
    id: 'preset-tx-01',
    x: 32,
    y: 24,
    width: 36,
    height: 50,
    itemName: 'Discarded Cotton & Synthetic Fabric Garment',
    confidence: 96.2,
    categoryCode: 'TX-01',
    categoryName: 'CATEGORY 6: TEXTILE (Reusable)',
    subType: 'Fabric/Cloth',
    bengaliExample: 'পুরনো কাপড়',
    natureCategory: 'Inorganic / Non-biodegradable',
    compositionDetail: 'Cotton Cellulose / Polyester Blended Woven Fibers',
    operationalStream: 'RECYCLABLE',
    processingPathway: 'Sanitization & Upcycling for Re-use, or Mechanical Carding into acoustic insulation',
    physicalState: 'Solid',
    environmentalRisk: 'Prevents massive landfill volume; synthetic fibers shed microplastics if dumped.',
    color: '#ec4899',
    badgeLabel: 'TX-01 • FABRIC & CLOTH',
    weightGrams: 340
  },

  // CATEGORY 7: ORGANIC (Compostable — optional scope)
  {
    id: 'preset-or-01',
    x: 34,
    y: 28,
    width: 32,
    height: 44,
    itemName: 'Organic Fruit & Vegetable Kitchen Scraps',
    confidence: 97.6,
    categoryCode: 'OR-01',
    categoryName: 'CATEGORY 7: ORGANIC (Compostable — optional scope)',
    subType: 'Food Waste',
    bengaliExample: 'খাদ্য বর্জ্য',
    natureCategory: 'Organic / Biodegradable',
    compositionDetail: 'Natural Plant Cellulose, Nitrogen & Biological Food Matter',
    operationalStream: 'COMPOSTABLE',
    processingPathway: 'Anaerobic Digestion for Biogas (CH4) Generation or Aerobic Industrial Composting',
    physicalState: 'Solid',
    environmentalRisk: 'Diverting from general landfill eliminates methane generation & toxic leachate.',
    color: '#10b981',
    badgeLabel: 'OR-01 • FOOD BIOWASTE',
    weightGrams: 140
  },
  {
    id: 'preset-or-02',
    x: 33,
    y: 27,
    width: 34,
    height: 46,
    itemName: 'Garden Leaves & Truncated Tree Branches',
    confidence: 96.9,
    categoryCode: 'OR-02',
    categoryName: 'CATEGORY 7: ORGANIC (Compostable — optional scope)',
    subType: 'Garden Waste',
    bengaliExample: 'পাতা, ডাল',
    natureCategory: 'Organic / Biodegradable',
    compositionDetail: 'Lignin, Hemicellulose & Dry Plant Carbon Biomass',
    operationalStream: 'COMPOSTABLE',
    processingPathway: 'Wood Chipper Shredding & High-Carbon Aerobic Windrow Composting',
    physicalState: 'Solid',
    environmentalRisk: 'Rich carbon source needed to balance wet nitrogenous food waste in composting.',
    color: '#10b981',
    badgeLabel: 'OR-02 • GARDEN BIOMASS',
    weightGrams: 280
  },

  // CATEGORY X: NON-REUSABLE / MANUAL WASTE (বাইরে রাখা)
  {
    id: 'preset-nr-01',
    x: 33,
    y: 25,
    width: 34,
    height: 50,
    itemName: 'Multi-Layer Metallized Chip Bag & Tetra Pak',
    confidence: 96.1,
    categoryCode: 'NR-01',
    categoryName: 'CATEGORY X: NON-REUSABLE / MANUAL WASTE (বাইরে রাখা)',
    subType: 'Composite Packaging',
    bengaliExample: 'চিপসের প্যাকেট, টেট্রা প্যাক',
    natureCategory: 'Inorganic / Non-biodegradable',
    compositionDetail: 'Laminated Metallized Aluminum Foil + BOPP Polypropylene Film + Paper Layer',
    operationalStream: 'LANDFILL_RESIDUAL',
    processingPathway: 'Engineered Sanitary Landfill Containment or High-Temp Cement Kiln Co-processing',
    physicalState: 'Solid',
    environmentalRisk: 'Non-recyclable due to fused multi-layer structure; must be segregated externally.',
    color: '#ef4444',
    badgeLabel: 'NR-01 • COMPOSITE PACKAGING',
    weightGrams: 18
  },
  {
    id: 'preset-nr-03',
    x: 34,
    y: 26,
    width: 32,
    height: 48,
    itemName: 'Sanitary & Medical Mask / Hygiene Waste',
    confidence: 97.3,
    categoryCode: 'NR-03',
    categoryName: 'CATEGORY X: NON-REUSABLE / MANUAL WASTE (বাইরে রাখা)',
    subType: 'Sanitary/Medical',
    bengaliExample: 'ডায়াপার, মাস্ক, ব্যান্ডেজ',
    natureCategory: 'Hazardous / Toxic',
    compositionDetail: 'Non-woven Polypropylene Fibers, Absorbent Polymer & Bio-hazardous Residues',
    operationalStream: 'LANDFILL_RESIDUAL',
    processingPathway: 'High-Temperature Incineration (1100°C) with Flue Gas Scrubbing or Autoclaving',
    physicalState: 'Solid',
    environmentalRisk: 'BIOHAZARD RISK: Pathogen contamination; must never be mixed with recyclable streams.',
    color: '#ef4444',
    badgeLabel: 'NR-03 • SANITARY / MEDICAL',
    weightGrams: 65
  },
  {
    id: 'preset-nr-04',
    x: 33,
    y: 25,
    width: 34,
    height: 48,
    itemName: 'Contaminated Oily Food Plastic Container',
    confidence: 95.7,
    categoryCode: 'NR-04',
    categoryName: 'CATEGORY X: NON-REUSABLE / MANUAL WASTE (বাইরে রাখা)',
    subType: 'Contaminated Mixed',
    bengaliExample: 'তেল/খাবার লেগে থাকা প্লাস্টিক',
    natureCategory: 'Inorganic / Non-biodegradable',
    compositionDetail: 'Degraded Polymer Matrix mixed with Rancid Organic Lipids & Oils',
    operationalStream: 'LANDFILL_RESIDUAL',
    processingPathway: 'Sanitary Landfill Disposal or Thermal Energy Recovery in Controlled Boiler Kilns',
    physicalState: 'Solid',
    environmentalRisk: 'Contaminates entire recycling wash baths if tossed into clean plastic bins.',
    color: '#ef4444',
    badgeLabel: 'NR-04 • CONTAMINATED PLASTIC',
    weightGrams: 110
  }
];
